export type BookMotif =
  | "lattice"
  | "corrosion"
  | "efficiency"
  | "network"
  | "boom"
  | "organization"
  | "schematic"
  | "flight"
  | "circuit"
  | "orbit"
  | "branches"
  | "wave"
  | "runner"
  | "gather"
  | "maze"
  | "fracture"
  | "continuum"
  | "windows"
  | "steps";

export type CatalogBook = {
  id: string;
  title: string;
  shortTitle: string;
  author: string;
  description: string;
  quote: string;
  quoteBy: string;
  format: string;
  availability: string;
  url: string;
  cover: string;
  accent: string;
  ink: string;
  motif: BookMotif;
  height: number;
  thickness: number;
  coverImage?: string;
  linkLabel?: string;
  living?: boolean;
};

export const catalog: CatalogBook[] = ([
  {
    id: "bilam",
    title: "బిలం",
    shortTitle: "బిలం",
    author: "సన్నపురెడ్డి వెంకటరామిరెడ్డి",
    description:
      "రాయలసీమ నేలను, రైతు జీవితాన్ని, గ్రామీణ సంబంధాలను మరియు మారుతున్న సమాజాన్ని ఆవిష్కరించే 19 కథల సంపుటి.",
    quote:
      "నేల, మనుషులు, జీవితం — రాయలసీమ కథల ప్రపంచం.",
    quoteBy: "Bala Books",
    format: "Paperback · 212 pages",
    availability: "Available now · ₹250",
    url: "https://balabooks.in/products/bilam-sannapureddy-venkataramireddy-telugu-stories",
    cover: "#5b241b",
    accent: "#d5a640",
    ink: "#f5ead8",
    motif: "branches",
  height: 2.18,
thickness: 0.26,
coverImage: "/books/bilam/BIlam%20Original%20front.jpg",
linkLabel: "Buy from Bala Books",
  },

  {
    id: "co-vaidurya-puram",
    title: "C/O వైఢూర్యపురం",
    shortTitle: "వైఢూర్యపురం",
    author: "రమాకాంత్ బుకా",
    description:
      "చరిత్ర, గుప్తనిధి, రహస్యం, సస్పెన్స్ కలిసిన ఆసక్తికరమైన తెలుగు నవల. 1724లో మొదలైన రహస్యం శతాబ్దాల తర్వాత కొత్త మలుపులు తీసుకుంటుంది.",
    quote:
      "కాలాన్ని దాటి వచ్చిన ఒక రహస్యం.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹170",
    url: "https://balabooks.in/products/untitled-12may_18-38",
    cover: "#172f49",
    accent: "#c89b3c",
    ink: "#f3ead7",
    motif: "maze",
    height: 2.10,
    thickness: 0.22,
    coverImage: "/books/C_O_vaiduryapuram/cover.png.png",
    linkLabel: "Buy from Bala Books",
  },

  {
    id: "keekaranyamlo-jinka",
    title: "కీకారణ్యంలో జింక",
    shortTitle: "కీకారణ్యంలో జింక",
    author: "తెలుగు అనువాదం: సింగం మల్లికార్జున రెడ్డి",
    description:
      "ఈశాన్య భారతదేశంలోని బోడో సమాజపు జీవితం, సంస్కృతి, అస్తిత్వం మరియు మానవ సంబంధాలను పరిచయం చేసే 12 కథల తెలుగు సంకలనం.",
    quote:
      "బ్రహ్మపుత్రా ఒడ్డున జీవించే మనుషుల కథలు.",
    quoteBy: "Bala Books",
    format: "Paperback · 110 pages",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/keekaranyamlo-jinka-bodo-kathalu-telugu",
    cover: "#334c39",
    accent: "#c9a34c",
    ink: "#f2ead9",
    motif: "lattice",
    height: 2.04,
    thickness: 0.20,
    coverImage: "/books/Keekaranyamlo%20jinka/cover.jpg.jpg",
    linkLabel: "Buy from Bala Books",
  },

  {
    id: "moon-light-killer",
    title: "మూన్‌లైట్ కిల్లర్",
    shortTitle: "మూన్‌లైట్ కిల్లర్",
    author: "సయ్యద్ ఆయేషా సుల్తానా",
    description:
      "హైదరాబాద్ నేపథ్యంలో సాగే ఉత్కంఠభరితమైన క్రైమ్ థ్రిల్లర్. ఒక రహస్య హత్యతో మొదలై పోలీసు దర్యాప్తు, అనుమానాలు, మానవ సంబంధాల చీకటి కోణాలతో చివరి వరకు సస్పెన్స్ కొనసాగించే నవల.",
    quote: "వెన్నెల రాత్రి… ఒక అంతుచిక్కని హత్య.",
    quoteBy: "Bala Books",
    format: "Paperback · 175 pages",
    availability: "Available now · ₹200",
    url: "https://balabooks.in/products/మూన్‌లైట్-కిల్లర్-సయ్యద్-ఆయేషా-సుల్తానా-తెలుగు-సస్పెన్స్-థ్రిల్లర్-నవల-bala-books",
    cover: "#182332",
    accent: "#d93632",
    ink: "#f5f1e8",
    motif: "fracture",
    height: 2.16,
    thickness: 0.23,
    coverImage: "/books/moon-light-killer.jpg",
    linkLabel: "Buy from Bala Books",
  },

  {
    id: "prashantha-pratyushalu",
    title: "ప్రశాంత ప్రత్యూషాలు",
    shortTitle: "ప్రశాంత ప్రత్యూషాలు",
    author: "బోరిస్ వసిల్యేవ్ · తెలుగు: నిడమర్తి ఉమారాజేశ్వరరావు",
    description:
      "ద్వితీయ ప్రపంచ యుద్ధ నేపథ్యంలో ఐదుగురు యువ సైనికురాళ్లు మరియు సార్జెంట్ మేజర్ వస్కోవ్ ఎదుర్కొనే అసాధారణ పోరాటాన్ని మానవీయ కోణంలో ఆవిష్కరించే రష్యన్ క్లాసిక్.",
    quote: "యుద్ధం వెనుక ఉన్న మనుషుల కథ.",
    quoteBy: "Bala Books",
    format: "Paperback · 170 pages",
    availability: "Available now · ₹200",
    url: "https://balabooks.in/products/prashantha-pratyushalu-telugu-novel",
    cover: "#6f593b",
    accent: "#d9a34c",
    ink: "#f5f2df",
    motif: "flight",
    height: 2.14,
    thickness: 0.23,
    coverImage: "/books/prashanta-pratyushalu.jpg",
    linkLabel: "Buy from Bala Books",
  },

  {
    id: "sulunthee",
    title: "సుళుందీ",
    shortTitle: "సుళుందీ",
    author: "రా. ముత్తు నాగు · తెలుగు: బొల్లి రామస్వామి రఘుపతి",
    description:
      "తమిళ సమాజపు మౌఖిక చరిత్ర, సామాజిక నిర్మాణం, అధికార సంబంధాలు మరియు ప్రజల ప్రతిఘటనను సృజనాత్మకంగా ఆవిష్కరించే విశిష్ట నవల.",
    quote: "చరిత్ర, మౌఖిక చరిత్ర, సృజనాత్మక కథనం కలిసిన నవల.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹550",
    url: "https://balabooks.in/products/sulunthee-tamil-fiction-literature-by-ra-mutthu-nagu-translated-by-bolli-ramaswami-raghupati",
    cover: "#17483f",
    accent: "#ef8929",
    ink: "#f3eee0",
    motif: "branches",
    height: 2.12,
    thickness: 0.34,
    coverImage: "/books/sulunthee.jpg",
    linkLabel: "Buy from Bala Books",
  },

  {
    id: "sahajeevanam",
    title: "సహజీవనం మరికొన్ని అనువాద కథలు",
    shortTitle: "సహజీవనం",
    author: "తెలుగు అనువాదం: ఏ.ఎన్. నాగేశ్వరరావు",
    description:
      "20 దేశాలకు చెందిన ప్రముఖ రచయితల 20 ప్రపంచ కథలను తెలుగు పాఠకులకు పరిచయం చేసే ప్రపంచకథాకరచాలనం సిరీస్ మూడవ భాగం.",
    quote: "20 దేశాలు. 20 కథలు. 20 జీవితాలు.",
    quoteBy: "Bala Books",
    format: "Paperback · 135 pages",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/products-sahahajeevanam-world-literature-telugu-stories",
    cover: "#8c6a43",
    accent: "#d8c82e",
    ink: "#fff9e7",
    motif: "gather",
    height: 2.06,
    thickness: 0.21,
    coverImage: "/books/sahajeevanam.png",
    linkLabel: "Buy from Bala Books",
  },

  {
    id: "sultana-kala",
    title: "సుల్తానా కల మరికొన్ని కథలు",
    shortTitle: "సుల్తానా కల",
    author: "తెలుగు అనువాదం: అచ్యుతుని రాజ్యశ్రీ",
    description:
      "ప్రపంచ సాహిత్యంలోని 30 వైవిధ్యభరితమైన కథలను తెలుగు పాఠకుల ముందుకు తీసుకొచ్చే ప్రత్యేక అనువాద కథా సంకలనం.",
    quote: "ఒకే పుస్తకంలో ముప్పై విభిన్న ప్రపంచాలు.",
    quoteBy: "Bala Books",
    format: "Paperback · 151 pages",
    availability: "Available now · ₹175",
    url: "https://balabooks.in/products/sultana-kala-marikonni-kathalu-telugu-translated-short-stories",
    cover: "#d8e5e5",
    accent: "#c3a91e",
    ink: "#172c34",
    motif: "windows",
    height: 2.08,
    thickness: 0.22,
    coverImage: "/books/sultana-kala.png",
    linkLabel: "Buy from Bala Books",
  },

  {
    id: "rupadharuni-yatralu",
    title: "రూపధరుడి యాత్రలు",
    shortTitle: "రూపధరుడి యాత్రలు",
    author: "హోమర్ · తెలుగు రూపం: కొడవటిగంటి కుటుంబరావు",
    description:
      "హోమర్ అమర మహాకావ్యం The Odyssey ఆధారంగా, ట్రాయ్ యుద్ధం తర్వాత రూపధరుడు తన స్వదేశానికి చేరుకునే పదేళ్ల సాహసయాత్రకు కొడవటిగంటి కుటుంబరావు అందించిన తెలుగు రూపం.",
    quote: "సముద్రాలు, ప్రమాదాలు, మాయాజాలాల మధ్య ఒక అపూర్వ సాహసయాత్ర.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/రూపధరుడి-యాత్రలు-the-odyssey-telugu-book-bala-books",
    cover: "#1d2930",
    accent: "#bc8b42",
    ink: "#f4f1e8",
    motif: "wave",
    height: 2.18,
    thickness: 0.24,
    coverImage: "/books/rupadharuni-yatralu.png",
    linkLabel: "Buy from Bala Books",
  },

  {
    id: "bhuvana-sundari",
    title: "భువన సుందరి",
    shortTitle: "భువన సుందరి",
    author: "హోమర్ ఇతిహాసం · తెలుగు రూపం: కొడవటిగంటి కుటుంబరావు",
    description:
      "The Iliad మరియు Trojan War నేపథ్యంతో భువనసుందరి, ట్రోయ్ నగరం, గ్రీకు వీరుల యుద్ధగాథకు కొడవటిగంటి కుటుంబరావు అందించిన ఆసక్తికరమైన తెలుగు రూపం.",
    quote: "ట్రోయ్ యుద్ధం — ప్రేమ, పరాక్రమం, వ్యూహం కలిసిన అమరగాథ.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹85",
    url: "https://balabooks.in/products/భువన-సుందరి-helen-of-troy-telugu-book-bala-books",
    cover: "#5c2d21",
    accent: "#d6a347",
    ink: "#f9f0df",
    motif: "flight",
    height: 2.20,
    thickness: 0.22,
    coverImage: "/books/bhuvana-sundari.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "ahimsa-jyothi",
    title: "Ahimsa Jyothi",
    shortTitle: "Ahimsa Jyothi",
    author: "Kodavatiganti Kutumba Rao",
    description: "A simple biography of Gautama Buddha written for younger readers and originally published as a serial in Chandamama magazine.",
    quote: "The life of Gautama Buddha for young readers.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/ahimsa-jyothi",
    cover: "#7d3d24",
    accent: "#d5a34a",
    ink: "#fff5dd",
    motif: "orbit",
    height: 2.03,
    thickness: 0.2,
    coverImage: "/books/ahimsa-jyothi/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "anamakudi-atmakatha",
    title: "Anamakudi Atmakatha",
    shortTitle: "Anamakudi Atmakatha",
    author: "Sa. Kandasami · Telugu: G.C. Jeevi",
    description: "A Telugu translation of Sa. Kandasami’s Tamil novel about ordinary lives, inner worlds and the unexpected turns connecting its characters.",
    quote: "Extraordinary moments within ordinary lives.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/anamakudi-atmakatha-telugu-novel-translated-from-tamil-by-g-c-jeevi-original-by-sa-kandasami",
    cover: "#6a392f",
    accent: "#d8a95a",
    ink: "#f8eddc",
    motif: "continuum",
    height: 2.02,
    thickness: 0.22,
    coverImage: "/books/anamakudi-atmakatha/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "aranya-puranam",
    title: "Aranya Puranam",
    shortTitle: "Aranya Puranam",
    author: "Rudyard Kipling · Telugu adaptation: Kodavatiganti Kutumba Rao",
    description: "A Telugu adaptation of Rudyard Kipling’s The Jungle Book, originally published as a serial in Chandamama magazine.",
    quote: "The Jungle Book in a Telugu adaptation.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/aranya-puranam",
    cover: "#315544",
    accent: "#c99742",
    ink: "#f2ead7",
    motif: "branches",
    height: 2.01,
    thickness: 0.21,
    coverImage: "/books/aranya-puranam/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "sarihaddu-kathalu",
    title: "Sarihaddu Kathalu",
    shortTitle: "Sarihaddu Kathalu",
    author: "R. Santha Sundari · Telugu: Nirmalananda",
    description: "A Telugu literary collection translated by Nirmalananda, presenting stories concerned with boundaries and lives that cross them.",
    quote: "Stories that cross visible and invisible boundaries.",
    quoteBy: "Bala Books",
    format: "Paperback · 150 pages",
    availability: "Available now · ₹200",
    url: "https://balabooks.in/products/bala-books-sarihaddu-kathalu-telugu-literature-book-paperback-150-pages-first-edition-translation-by-nirmalananda",
    cover: "#7d2423",
    accent: "#d2ad61",
    ink: "#fff1dc",
    motif: "fracture",
    height: 2,
    thickness: 0.22,
    coverImage: "/books/sarihaddu-kathalu/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "divi-nundi-bhuviki",
    title: "Divi Nundi Bhuviki",
    shortTitle: "Divi Nundi Bhuviki",
    author: "Arandai Narayanan · Telugu: G.C. Jeevi",
    description: "A Telugu translation of a Tamil novel tracing the legendary actress Savitri’s journey from celebrated stardom to difficult later years.",
    quote: "A life between stardom and obscurity.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/divi-nundi-bhuviki-telugu-novel-based-on-legendary-actress-life-by-arandanarayanan-translated-by-g-c-jeevi",
    cover: "#7a4135",
    accent: "#d9a64a",
    ink: "#f7eadc",
    motif: "steps",
    height: 1.99,
    thickness: 0.22,
    coverImage: "/books/divi-nundi-bhuviki/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "duhkhapu-rangu",
    title: "Duhkhapu Rangu",
    shortTitle: "Duhkhapu Rangu",
    author: "Vanaja Tatineni",
    description: "Twenty-three stories examining women’s lives, struggles, aspirations, solidarity and self-respect amid social and political realities.",
    quote: "Twenty-three stories of women’s lives and resilience.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹265",
    url: "https://balabooks.in/products/duhkhapu-rangu-telugu-short-stories-collection-by-vanaja-tatineni-womens-social-issues",
    cover: "#4e2936",
    accent: "#d19a51",
    ink: "#f9ebdf",
    motif: "gather",
    height: 1.98,
    thickness: 0.25,
    coverImage: "/books/duhkhapu-rangu/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "eesaramma-koduku",
    title: "Eesaramma Koduku Mariyu Itara Kathalu",
    shortTitle: "Eesaramma Koduku",
    author: "Thimmaraju",
    description: "Stories rooted in Nandyal, shaped by Rayalaseema speech, village memories, affection, humour, belief and everyday relationships.",
    quote: "Stories spoken in the voice of Nandyal.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹200",
    url: "https://balabooks.in/products/eesaramma-koduku-mariyu-itara-kathalu-contemporary-stories",
    cover: "#4c3126",
    accent: "#c9a35e",
    ink: "#f5ead7",
    motif: "network",
    height: 1.97,
    thickness: 0.22,
    coverImage: "/books/eesaramma-koduku/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "first-love",
    title: "First Love Marikonni Kathalu",
    shortTitle: "First Love",
    author: "Skybaba",
    description: "A collection of Telugu love stories attentive to tenderness, struggle, emotional wounds, Telangana language and the texture of Urdu words.",
    quote: "Tender stories of love, struggle and memory.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹170",
    url: "https://balabooks.in/products/first-love-marikonni-kathalu-by-skybaba",
    cover: "#5c1f2d",
    accent: "#d9a24d",
    ink: "#fff0e1",
    motif: "wave",
    height: 1.96,
    thickness: 0.21,
    coverImage: "/books/first-love/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "gajadanthi",
    title: "Gajadanthi Marinni Kathalu",
    shortTitle: "Gajadanthi",
    author: "Sri Sudhamayi",
    description: "A varied story collection moving through family bonds, loss, science, suspense, memory and the emotions hidden within everyday life.",
    quote: "Emotion, science and suspense across many lives.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹170",
    url: "https://balabooks.in/products/gajadanthi-marinni-kathalu-by-srisudhamayi",
    cover: "#3d414d",
    accent: "#d4a85a",
    ink: "#f2eee4",
    motif: "orbit",
    height: 1.95,
    thickness: 0.21,
    coverImage: "/books/gajadanthi/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "hyderabad-to-shikago",
    title: "Hyderabad to Shikago",
    shortTitle: "Hyderabad to Shikago",
    author: "Shantisri Benarji",
    description: "A practical travelogue spanning Berlin and American cities, combining observations of places and food with useful planning details for travellers.",
    quote: "A travelogue that doubles as a companion on the road.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/hyderabad-to-shikago-travelogue-by-shantisri-benarji",
    cover: "#273d58",
    accent: "#ca9b43",
    ink: "#eef1ed",
    motif: "flight",
    height: 1.94,
    thickness: 0.21,
    coverImage: "/books/hyderabad-to-shikago/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "jataka-kathalu-1",
    title: "Jataka Kathalu 1",
    shortTitle: "Jataka Kathalu 1",
    author: "Kodavatiganti Kutumba Rao",
    description: "The first volume of Buddhist Jataka tales about the Buddha’s previous births, originally serialized in Chandamama magazine.",
    quote: "The first Chandamama volume of Jataka tales.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/jataka-kathalu-1",
    cover: "#725029",
    accent: "#d5aa55",
    ink: "#f7edd9",
    motif: "lattice",
    height: 2.03,
    thickness: 0.2,
    coverImage: "/books/jataka-kathalu-1/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "jataka-kathalu-2",
    title: "Jataka Kathalu 2",
    shortTitle: "Jataka Kathalu 2",
    author: "Kodavatiganti Kutumba Rao",
    description: "The second volume of Buddhist Jataka tales about the Buddha’s previous births, originally serialized in Chandamama magazine.",
    quote: "The second Chandamama volume of Jataka tales.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/jataka-kathalu-2",
    cover: "#4d6135",
    accent: "#d0a24b",
    ink: "#f4eedc",
    motif: "lattice",
    height: 2.02,
    thickness: 0.2,
    coverImage: "/books/jataka-kathalu-2/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "kalpita-betala-kathalu",
    title: "Kalpita Betala Kathalu",
    shortTitle: "Kalpita Betala Kathalu",
    author: "Bellamkonda Nageswara Rao",
    description: "Thirty illustrated Betala stories for children, written in simple and accessible language.",
    quote: "Thirty illustrated Betala stories for children.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/kalpita-betala-kathalu",
    cover: "#512d5e",
    accent: "#d3a54b",
    ink: "#fbefdb",
    motif: "maze",
    height: 2.01,
    thickness: 0.21,
    coverImage: "/books/kalpita-betala-kathalu/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "kathaa-kadambam-1",
    title: "Kathaa Kadambam",
    shortTitle: "Kathaa Kadambam",
    author: "Telugu: R. Santha Sundari · Compiled by M.B. Usha Prathyusha",
    description: "An anthology of twenty-three short stories translated into Telugu by R. Santha Sundari.",
    quote: "Twenty-three translated short stories.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/kathaa-kadambam-an-anthology-of-short-stories-by-r-santha-sundari",
    cover: "#393f58",
    accent: "#d1a558",
    ink: "#f4ece1",
    motif: "windows",
    height: 2,
    thickness: 0.23,
    coverImage: "/books/kathaa-kadambam-1/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "kathaa-kadambam-2",
    title: "Kathaa Kadambam 2",
    shortTitle: "Kathaa Kadambam 2",
    author: "Telugu: G.C. Jeevi · Compiled by M.B. Usha Prathyusha",
    description: "An anthology of twenty-six translated short stories by G.C. Jeevi, selected and compiled by M.B. Usha Prathyusha.",
    quote: "Twenty-six stories in Telugu translation.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹250",
    url: "https://balabooks.in/products/kathaa-kadambam-2-an-anthology-of-translated-short-stories-in-telugu-by-g-c-jeevi-compiled-by-m-b-usha-prathyusha",
    cover: "#2e4d51",
    accent: "#cda34f",
    ink: "#f3eee2",
    motif: "windows",
    height: 1.99,
    thickness: 0.24,
    coverImage: "/books/kathaa-kadambam-2/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "kathaa-kadambam-3",
    title: "Kathaa Kadambam 3",
    shortTitle: "Kathaa Kadambam 3",
    author: "Telugu: G.C. Jeevi · Compiled by M.B. Usha Prathyusha",
    description: "A selection of translated short stories by G.C. Jeevi, carefully compiled by M.B. Usha Prathyusha.",
    quote: "A carefully compiled anthology of translated stories.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹250",
    url: "https://balabooks.in/products/kathaa-kadambam-3-an-anthology-of-short-stories-in-telugu-by-g-c-jeevi-compiled-by-m-b-usha-prathyusha",
    cover: "#5a3044",
    accent: "#d2a553",
    ink: "#f8ece0",
    motif: "windows",
    height: 1.98,
    thickness: 0.24,
    coverImage: "/books/kathaa-kadambam-3/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "ma-voori-kathalu",
    title: "Ma Voori Kathalu",
    shortTitle: "Ma Voori Kathalu",
    author: "Dr. V.R. Rasani",
    description: "Stories that return readers to village life, local language, social characters and the lived world of Kuravapalle.",
    quote: "Village lives carried through language and memory.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/ma-voori-kathalu-by-dr-v-r-rasani-paperback",
    cover: "#68462e",
    accent: "#d1a24e",
    ink: "#f6ebd9",
    motif: "gather",
    height: 1.97,
    thickness: 0.22,
    coverImage: "/books/ma-voori-kathalu/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "mitruni-hrudayam",
    title: "Mitruni Hrudayam",
    shortTitle: "Mitruni Hrudayam",
    author: "Emmanuil Kazakevich · Telugu: Giduthoori Sooryam",
    description: "An anti-war novel following battalion commander Pavel Akimov and interpreter Anichka Belozyorova through love, marriage and wartime loss.",
    quote: "Love and loss amid the Great Patriotic War.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹300",
    url: "https://balabooks.in/products/mitruni-hrudayam-by-emmanuil-kazakevich-telugu-translation-by-giduthoori-sooryam",
    cover: "#3e4858",
    accent: "#d0a457",
    ink: "#f1ece2",
    motif: "flight",
    height: 1.96,
    thickness: 0.27,
    coverImage: "/books/mitruni-hrudayam/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "naa-peru-bhagatsingh",
    title: "Naa Peru Bhagatsingh",
    shortTitle: "Naa Peru Bhagatsingh",
    author: "Telugu: Mohan Talari",
    description: "A Telugu translation of Bhagat Singh’s jail diary and other writings by Mohan Talari.",
    quote: "Bhagat Singh’s jail diary and writings in Telugu.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹250",
    url: "https://balabooks.in/products/naa-peru-bhagatsingh",
    cover: "#6a2a27",
    accent: "#d7a141",
    ink: "#f8ecd9",
    motif: "fracture",
    height: 1.95,
    thickness: 0.24,
    coverImage: "/books/naa-peru-bhagatsingh/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "pallebadi",
    title: "Pallebadi",
    shortTitle: "Pallebadi",
    author: "Sammeta Umadevi",
    description: "An illustrated novel for children written by Sammeta Umadevi in simple Telugu.",
    quote: "An illustrated village-school novel for children.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹100",
    url: "https://balabooks.in/products/pallebadi",
    cover: "#305244",
    accent: "#d2a84f",
    ink: "#f2ecdb",
    motif: "steps",
    height: 1.94,
    thickness: 0.19,
    coverImage: "/books/pallebadi/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "palukudari-payanam",
    title: "Palukudari Payanam",
    shortTitle: "Palukudari Payanam",
    author: "Bava Chelladurai · Telugu: Gillella Balaji",
    description: "Tamil literary essays reflecting on life, society and the search for clarity, translated into Telugu by Gillella Balaji.",
    quote: "Essays that offer companionship and perspective.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹250",
    url: "https://balabooks.in/products/palukudari-payanam-tamil-literary-essays-by-bava-chelladurai-telugu-translation-by-gillella-balaji-paperback",
    cover: "#49384d",
    accent: "#cda052",
    ink: "#f4ecdf",
    motif: "continuum",
    height: 2.03,
    thickness: 0.24,
    coverImage: "/books/palukudari-payanam/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "pasivadi-paga",
    title: "Pasivadi Paga",
    shortTitle: "Pasivadi Paga",
    author: "V. Bogomolov · Telugu: Rallabandi Venkateswara Rao",
    description: "A Telugu translation of Ivan, following a young Soviet military scout undertaking dangerous missions during the Second World War.",
    quote: "War seen through the courage of a young scout.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/pasivadi-paga-telugu-translation-of-ivan-by-v-bogomolov-world-war-ii-story-book-paperback",
    cover: "#3d4b59",
    accent: "#d0a251",
    ink: "#f2eee5",
    motif: "runner",
    height: 2.02,
    thickness: 0.22,
    coverImage: "/books/pasivadi-paga/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "pelli-kathalu",
    title: "Pelli Kathalu",
    shortTitle: "Pelli Kathalu",
    author: "Acharya Marreboyina Jayadev",
    description: "A collection of Telugu short stories exploring marriage, relationships, social dynamics and cultural traditions.",
    quote: "Marriage and relationships through contemporary stories.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/pelli-kathalu-telugu-short-stories-collection-by-acharya-marreboyina-jayadev-paperback",
    cover: "#31513c",
    accent: "#d1a44e",
    ink: "#f2ecdc",
    motif: "gather",
    height: 2.01,
    thickness: 0.21,
    coverImage: "/books/pelli-kathalu/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "prapancha-katha-karachalanam-1",
    title: "ప్రపంచ కథా కరచాలనం 1",
    shortTitle: "కథా కరచాలనం 1",
    author: "తెలుగు: అచ్యుతుని రాజ్యశ్రీ · కథల సేకరణ: ఎం.బి. ఉషా ప్రత్యూష",
    description: "ముప్పై దేశాల నుంచి ఎంపిక చేసిన ముప్పై ప్రపంచ కథలను అచ్యుతుని రాజ్యశ్రీ తెలుగు పాఠకులకు అందించిన అనువాద సంకలనం.",
    quote: "30 దేశాలు · 30 కథలు · 30 జీవితాలు.",
    quoteBy: "Bala Books",
    format: "Paperback · 170 pages",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/prapancha-katha-karachalanam-1",
    cover: "#6f4234",
    accent: "#d2a047",
    ink: "#f7ead9",
    motif: "network",
    height: 2,
    thickness: 0.22,
    coverImage: "/books/prapancha-katha-karachalanam-1/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "maro-kappu-coffee",
    title: "మరో కప్పు కాఫీ మరికొన్ని అనువాద కథలు",
    shortTitle: "మరో కప్పు కాఫీ",
    author: "తెలుగు: కాలిపు వీరభద్రుడు",
    description: "ఇరవై మూడు దేశాల నుంచి ఎంపిక చేసిన ఇరవై మూడు అంతర్జాతీయ కథలను సహజమైన తెలుగులో అందించిన ప్రపంచ కథా కరచాలనం రెండవ భాగం.",
    quote: "23 దేశాల నుంచి 23 అంతర్జాతీయ కథలు.",
    quoteBy: "Bala Books",
    format: "Paperback · 141 pages",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/maro-kappu-coffee-telugu-translated-stories-vol-2",
    cover: "#623626",
    accent: "#d1a45a",
    ink: "#f7ecdd",
    motif: "wave",
    height: 1.99,
    thickness: 0.21,
    coverImage: "/books/maro-kappu-coffee/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "railubandi-kathanalu",
    title: "Railubandi Kathanalu",
    shortTitle: "Railubandi Kathanalu",
    author: "Subbu R.V.",
    description: "Stories centred on working lives, traditional occupations and the enduring value of labour.",
    quote: "Working lives are the enduring stories of existence.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹200",
    url: "https://balabooks.in/products/railubandi-kathanalu-by-subbu-rv-paperback-subbu-rv-sep-04-2025",
    cover: "#394c55",
    accent: "#cda04b",
    ink: "#f1ece0",
    motif: "runner",
    height: 1.98,
    thickness: 0.22,
    coverImage: "/books/railubandi-kathanalu/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "sanyasiniki-premato",
    title: "Sanyasiniki Premato",
    shortTitle: "Sanyasiniki Premato",
    author: "Shiv K. Kumar · Telugu: A. Krishna",
    description: "A Telugu translation of Shiv K. Kumar’s short stories exploring complex human emotions and relationships.",
    quote: "Stories of human emotion and relationship.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹175",
    url: "https://balabooks.in/products/sanyasiniki-premato-telugu-short-stories-collection-written-by-shiv-k-kumar-translated-by-a-krishna",
    cover: "#58404c",
    accent: "#d0a45c",
    ink: "#f5ecdf",
    motif: "continuum",
    height: 1.97,
    thickness: 0.22,
    coverImage: "/books/sanyasiniki-premato/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "seema-swaralu",
    title: "Seema Swaralu",
    shortTitle: "Seema Swaralu",
    author: "Dr. V.R. Rasani",
    description: "A collection rooted in Rayalaseema, giving voice to rural and working-class lives, social realities, language and local traditions.",
    quote: "The voices and lived realities of Rayalaseema.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹350",
    url: "https://balabooks.in/products/seema-swaralu-a-captivating-collection-of-stories-by-the-eminent-writer-dr-v-r-rasani",
    cover: "#553a2b",
    accent: "#d2a351",
    ink: "#f5ead9",
    motif: "branches",
    height: 1.96,
    thickness: 0.29,
    coverImage: "/books/seema-swaralu/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "swarga-narakam",
    title: "Swarga Narakam",
    shortTitle: "Swarga Narakam",
    author: "Sujatha · Telugu: G.C. Jeevi",
    description: "A Telugu science-fiction novel about a man transported to a mysterious island whose technology and customs challenge his sense of reality.",
    quote: "An island poised between heaven and hell.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/swarga-narakam-telugu-science-fiction-novel-by-sujatha-translated-by-g-c-jeevi",
    cover: "#263d55",
    accent: "#cda04b",
    ink: "#f0eee7",
    motif: "circuit",
    height: 1.95,
    thickness: 0.22,
    coverImage: "/books/swarga-narakam/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "teeram-chere-daaka",
    title: "Teeram Chere Daaka",
    shortTitle: "Teeram Chere Daaka",
    author: "Dinnesh",
    description: "Thirteen women-centred stories considering relationships, social restrictions and changing aspirations in urban and semi-urban life.",
    quote: "Thirteen stories of changing lives and relationships.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹200",
    url: "https://balabooks.in/products/teeram-chere-daaka-contemporary-stories-of-love-in-all-its-forms-by-dinnesh",
    cover: "#3c4f5b",
    accent: "#d1a34d",
    ink: "#f2ece1",
    motif: "wave",
    height: 1.94,
    thickness: 0.22,
    coverImage: "/books/teeram-chere-daaka/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "udhyamam",
    title: "Udhyamam",
    shortTitle: "Udhyamam",
    author: "Raj Gill · Telugu: Sahavasi",
    description: "A political novel based on the Akali Dal movement, the Golden Temple siege and Operation Blue Star, examining religion, history and power.",
    quote: "A political novel rooted in turbulent history.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/udhyamam-telugu-translated-novel-originally-written-by-raj-gil-telugu-translation-by-sahavasi",
    cover: "#6c302a",
    accent: "#d1a048",
    ink: "#f7ebdc",
    motif: "fracture",
    height: 2.03,
    thickness: 0.23,
    coverImage: "/books/udhyamam/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "vaddi-vyapari-bharya",
    title: "Vaddi Vyapari Bharya",
    shortTitle: "Vaddi Vyapari Bharya",
    author: "Fyodor Dostoevsky · Telugu: Aluri Bhujanga Rao",
    description: "A Telugu translation of Dostoevsky’s psychological novella about an ageing moneylender, his young wife, remorse and tragic consequences.",
    quote: "A psychological portrait of love, remorse and loss.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹65",
    url: "https://balabooks.in/products/vaddi-vyapari-bharya-telugu-novel-by-aluri-bhujangarao-translated-from-dostoevsky",
    cover: "#46343d",
    accent: "#cfa455",
    ink: "#f4ece2",
    motif: "maze",
    height: 2.02,
    thickness: 0.19,
    coverImage: "/books/vaddi-vyapari-bharya/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "viswakatha-veedhi",
    title: "Viswakatha Veedhi",
    shortTitle: "Viswakatha Veedhi",
    author: "Telugu: Puripanda Appalaswamy",
    description: "A collection of translated stories by Puripanda Appalaswamy.",
    quote: "World stories in Telugu translation.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹450",
    url: "https://balabooks.in/products/viswakatha-veedhi-by-puripanda-appalaswamy-paperback",
    cover: "#394b54",
    accent: "#d0a251",
    ink: "#f1ece2",
    motif: "network",
    height: 2.01,
    thickness: 0.31,
    coverImage: "/books/viswakatha-veedhi/cover.jpg",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "yamam",
    title: "యామం",
    shortTitle: "యామం",
    author: "ఎస్. రామకృష్ణన్ · తెలుగు: జిల్లేళ్ళ బాలాజీ",
    description: "పద్దెనిమిదవ శతాబ్దపు వలస భారతదేశంలో ఒకే రాత్రి సాగే ఐదు జీవితకథలను మేజిక్ రియలిజంతో అల్లిన చారిత్రక తమిళ నవల తెలుగు అనువాదం.",
    quote: "ఒక రాత్రి — ఐదు జీవితాలు — ఒక చారిత్రక సంధికాలం.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹375",
    url: "https://balabooks.in/products/yamam-s-ramakrishnans-tamil-novel-telugu-translation-by-gillella-balaji",
    cover: "#233746",
    accent: "#cda04c",
    ink: "#f0ece2",
    motif: "orbit",
    height: 2,
    thickness: 0.3,
    coverImage: "/books/yamam/cover.png",
    linkLabel: "Buy from Bala Books",
  },
  {
    id: "swarnamukhi-kathalu",
    title: "స్వర్ణముఖి కథలు",
    shortTitle: "స్వర్ణముఖి కథలు",
    author: "డా. వి.ఆర్. రాసాని",
    description: "స్వర్ణముఖి నది స్వయంగా కథకురాలిగా మారి రాయలసీమ ప్రకృతి, చరిత్ర, గ్రామీణ జీవితం, కాలుష్యం మరియు పర్యావరణ విధ్వంసాన్ని చెప్పే కథా సంకలనం.",
    quote: "నది చెప్పిన నేల, నీరు, మనిషి కథలు.",
    quoteBy: "Bala Books",
    format: "Paperback",
    availability: "Available now · ₹150",
    url: "https://balabooks.in/products/swarnamukhi-kathalu-telugu-stories-vr-rasani",
    cover: "#27483e",
    accent: "#d0a14a",
    ink: "#f1ecdc",
    motif: "branches",
    height: 1.99,
    thickness: 0.22,
    coverImage: "/books/swarnamukhi-kathalu/cover.png",
    linkLabel: "Buy from Bala Books",
  },
] satisfies CatalogBook[]).sort(
  (left, right) => right.height - left.height,
);
